name: Deploy and Run Telegram Bot

on:
  push:
    branches:
      - main
  schedule:
    # Schedule to run the bot every hour (change as per your requirement)
    - cron: '0 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the bot temporarily
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          python bot.py &
          sleep 300  # Keeps the bot alive for 5 minutes (adjust as needed)
