name: Deploy and Run Telegram Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Update requirements.txt
        run: pip-compile --upgrade requirements.in

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest

      - name: Build Docker image
        run: docker build -t telegram-bot .

      - name: Push Docker image to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag telegram-bot ghcr.io/${{ github.repository }}/telegram-bot:latest
          docker push ghcr.io/${{ github.repository }}/telegram-bot:latest

      - name: Deploy to server
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          ssh user@server 'docker pull ghcr.io/${{ github.repository }}/telegram-bot:latest && docker run -d --env TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} telegram-bot'
